import {useState} from 'react';
import type {CSSProperties} from 'react';
import {
  ArrowRight,BookOpen,CalendarCheck2,CalendarDays,Check,Clock3,DollarSign,ExternalLink,
  FileText,Heart,Luggage,Map,MapPin,Navigation,Plus,Receipt,Search,Settings2,ShieldCheck,
  Trash2,UserPlus,Users,Wallet
} from 'lucide-react';
import {openGoogleMaps} from '../maps';
import {
  balances,calculateSettlements,dateLabel,memberName,money,minutesLabel,sortActivitiesChronologically,
  tripDates,tripProgress
} from '../model';
import type {ActivityStatus,MemberRole,PackingItem,Trip,View} from '../model';
import {
  Avatar,BudgetSummary,Empty,Page,PanelHead,StatusBadge,categoryIcon,displayTime,relativeDate,
  reservationIcon,splitLabel
} from './shared';

export function Overview({trip,countdown,spent,packed,confirmed,currentUserId,canEdit,canManageTrip,onNavigate,onTripSettings,onAddActivity}:{trip:Trip;countdown:number;spent:number;packed:number;confirmed:number;currentUserId:string;canEdit:boolean;canManageTrip:boolean;onNavigate:(view:View)=>void;onTripSettings:()=>void;onAddActivity:()=>void}){
  const next=sortActivitiesChronologically(trip.activities.filter(item=>item.status!=='suggested'&&item.status!=='completed')).slice(0,3);
  const upcomingReservations=[...trip.reservations].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)).slice(0,2);
  const progress=tripProgress(trip);
  const budgetPct=trip.budget>0?Math.min(100,Math.round(spent/trip.budget*100)):spent>0?100:0;
  const active=trip.members.filter(member=>member.status==='active');
  const countdownText=countdown>0?`${countdown} days to go`:countdown===0?'Trip starts today':'Trip underway or completed';
  return <>
    <section className="wl-hero">
      <div className="wl-hero-copy"><span className="wl-kicker">{countdownText}</span><h1>{trip.name}</h1><p>{trip.description||'A shared place for the practical details and the fun parts of the trip.'}</p><div className="wl-hero-meta"><span><MapPin size={15}/>{trip.destination}</span><span><CalendarDays size={15}/>{dateLabel(trip.startDate,{month:'short',day:'numeric'})} – {dateLabel(trip.endDate,{month:'short',day:'numeric',year:'numeric'})}</span><span><Users size={15}/>{active.length} traveler{active.length===1?'':'s'}</span></div></div>
      {(canEdit||canManageTrip)&&<div className="wl-hero-actions">{canEdit&&<button onClick={onAddActivity}><Plus size={16}/> Add plan</button>}{canManageTrip&&<button className="secondary" onClick={onTripSettings}><Settings2 size={16}/> Trip settings</button>}</div>}
    </section>
    <section className="wl-stat-grid" aria-label="Trip summary"><Stat label="Trip progress" value={`${progress}%`} note={`${confirmed} confirmed or completed plans`} progress={progress}/><Stat label="Budget used" value={money(spent)} note={trip.budget>0?(spent>trip.budget?`${money(spent-trip.budget)} over budget`:`${money(trip.budget-spent)} remaining`):'No trip budget set'} progress={budgetPct}/><Stat label="Packing" value={`${packed}/${trip.packing.length}`} note="items ready" progress={Math.round(packed/Math.max(trip.packing.length,1)*100)}/><Stat label="Ideas waiting" value={`${trip.activities.filter(item=>item.status==='suggested').length}`} note="ready for a group decision" progress={0}/></section>
    <div className="wl-dashboard-grid">
      <section className="wl-panel wl-next-plans"><PanelHead eyebrow="Coming up" title="Next on the itinerary" action={<button onClick={()=>onNavigate('itinerary')}>Full itinerary <ArrowRight size={14}/></button>}/>{next.map(item=><button className="wl-next-row" key={item.id} onClick={()=>openGoogleMaps(item.location,'directions')}><span className={`wl-category ${item.category}`}>{categoryIcon(item.category)}</span><div><b>{item.title}</b><small>{dateLabel(item.date)} · {displayTime(item.time)} · {item.location}</small></div><strong>{item.cost===0?'Free':money(item.cost)}</strong><Navigation size={15}/></button>)}{next.length===0&&<Empty title="Nothing scheduled yet" text="Add a plan or promote one of the group’s ideas when the itinerary is ready."/>}</section>
      <section className="wl-panel"><PanelHead eyebrow="Travel party" title="Who’s going" action={<button onClick={()=>onNavigate('travelers')}>Manage <ArrowRight size={14}/></button>}/><div className="wl-member-stack">{active.map(member=><div key={member.id}><Avatar member={member}/><span><b>{member.name}{member.id===currentUserId?' (you)':''}</b><small>{member.role}</small></span></div>)}</div>{trip.members.some(member=>member.status==='pending')&&<p className="wl-panel-note">{trip.members.filter(member=>member.status==='pending').length} invitation{trip.members.filter(member=>member.status==='pending').length===1?'':'s'} pending locally</p>}</section>
      <section className="wl-panel"><PanelHead eyebrow="Bookings" title="Reservations" action={<button onClick={()=>onNavigate('notes')}>View all <ArrowRight size={14}/></button>}/><div className="wl-reservation-mini">{upcomingReservations.map(item=><button key={item.id} onClick={()=>openGoogleMaps(item.location)}><span>{reservationIcon(item.type)}</span><div><b>{item.title}</b><small>{dateLabel(item.date)} · {displayTime(item.time)}</small></div><ExternalLink size={14}/></button>)}{upcomingReservations.length===0&&<p className="wl-panel-note">No bookings have been added yet.</p>}</div></section>
      <section className="wl-panel wl-together"><PanelHead eyebrow="Group planning" title="Decisions to make" action={<button onClick={()=>onNavigate('ideas')}>Open ideas <ArrowRight size={14}/></button>}/><div className="wl-decision-summary"><span><Heart size={20}/></span><div><strong>{trip.activities.filter(item=>item.status==='suggested').length}</strong><b>open suggestions</b><p>Active travelers can vote; editors decide when an idea becomes a real plan.</p></div></div></section>
    </div>
  </>;
}

function Stat({label,value,note,progress}:{label:string;value:string;note:string;progress:number}){
  return <div className="wl-stat"><span>{label}</span><strong>{value}</strong><small>{note}</small>{progress>0&&<div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,progress)}><i style={{width:`${Math.min(100,progress)}%`}}/></div>}</div>;
}

export function Itinerary({trip,selectedDate,setSelectedDate,canEdit,onAdd,onEdit,onDelete,onStatus}:{trip:Trip;selectedDate:string;setSelectedDate:(date:string)=>void;canEdit:boolean;onAdd:(date:string)=>void;onEdit:(id:string)=>void;onDelete:(id:string)=>void;onStatus:(id:string,status:ActivityStatus)=>void}){
  const dates=tripDates(trip.startDate,trip.endDate);
  const dayItems=sortActivitiesChronologically(trip.activities.filter(item=>item.date===selectedDate&&item.status!=='suggested'));
  return <Page title="Day by day" eyebrow="Your route" description="One chronological timeline for the plans the trip has actually committed to." action={canEdit?<button className="wl-primary" onClick={()=>onAdd(selectedDate)}><Plus size={16}/> Add activity</button>:undefined}>
    <div className="wl-day-tabs" role="tablist" aria-label="Trip days">{dates.map((date,index)=><button role="tab" aria-selected={date===selectedDate} key={date} className={date===selectedDate?'active':''} onClick={()=>setSelectedDate(date)}><small>Day {index+1}</small><b>{dateLabel(date,{weekday:'short',month:'short',day:'numeric'})}</b><span>{trip.activities.filter(item=>item.date===date&&item.status!=='suggested').length} plans</span></button>)}</div>
    <div className="wl-itinerary-layout"><section className="wl-timeline" aria-label={`Itinerary for ${dateLabel(selectedDate,{weekday:'long',month:'long',day:'numeric'})}`}>{dayItems.length===0&&<Empty title="This day is wide open" text="Add a plan, or promote one of the group’s ideas." action={canEdit?<button onClick={()=>onAdd(selectedDate)}>Add activity</button>:undefined}/>} {dayItems.map((item,index)=><div className="wl-timeline-row" key={item.id}><div className="wl-time"><b>{displayTime(item.time)}</b>{index<dayItems.length-1&&<i/>}</div><button className={`wl-status-dot ${item.status}`} onClick={()=>canEdit&&onStatus(item.id,item.status==='completed'?'confirmed':'completed')} disabled={!canEdit} aria-label={item.status==='completed'?`Reopen ${item.title}`:`Mark ${item.title} complete`}>{item.status==='completed'?<Check size={14}/>:<span/>}</button><article className={`wl-activity-card ${item.status==='completed'?'completed':''}`}><div className="wl-activity-top"><span className={`wl-category ${item.category}`}>{categoryIcon(item.category)}</span><div className="wl-activity-title"><div><StatusBadge status={item.status}/><small>Added by {memberName(trip,item.createdBy)}</small></div><h3>{item.title}</h3><button className="wl-location" onClick={()=>openGoogleMaps(item.location)}><MapPin size={13}/>{item.location||'No location'}<ExternalLink size={12}/></button></div>{canEdit&&<div className="wl-card-actions"><button onClick={()=>onEdit(item.id)} aria-label={`Edit ${item.title}`}><Settings2 size={15}/></button><button onClick={()=>onDelete(item.id)} aria-label={`Delete ${item.title}`}><Trash2 size={15}/></button></div>}</div>{item.note&&<p>{item.note}</p>}<div className="wl-activity-foot"><span><Clock3 size={13}/>{minutesLabel(item.durationMinutes)}</span><span><DollarSign size={13}/>{item.cost===0?'Free':money(item.cost)}</span><span><Users size={13}/>{item.attendeeIds.length} going</span>{item.location&&<button onClick={()=>openGoogleMaps(item.location,'directions')}><Navigation size={13}/> Directions</button>}</div></article></div>)}</section>
      <aside className="wl-day-aside"><div className="wl-route-card"><div className="wl-route-art"><Map size={28}/><span>{dayItems.length}</span></div><h3>{dateLabel(selectedDate,{weekday:'long',month:'long',day:'numeric'})}</h3><p>{dayItems.length?`${dayItems.length} stops · ${money(dayItems.reduce((sum,item)=>sum+item.cost,0))} estimated`:'No stops yet'}</p>{dayItems[0]?.location&&<button onClick={()=>openGoogleMaps(dayItems[0].location)}><Map size={15}/> Open first stop in Google Maps</button>}</div><div className="wl-day-team"><h3>Trip travelers</h3><div>{trip.members.filter(member=>member.status==='active').map(member=><Avatar key={member.id} member={member} small/>)}</div><p>Attendance is stored on each plan, so a traveler can skip one activity without leaving the trip.</p></div><div className="wl-tip-card"><span>Local rhythm</span><h3>Leave room between plans.</h3><p>A realistic day is more useful than a timeline packed edge-to-edge with saved places.</p></div></aside>
    </div>
  </Page>;
}

export function Ideas({trip,currentUserId,canEdit,canVote,onAdd,onVote,onPromote,onEdit,onDelete}:{trip:Trip;currentUserId:string;canEdit:boolean;canVote:boolean;onAdd:()=>void;onVote:(id:string)=>void;onPromote:(id:string,status:ActivityStatus)=>void;onEdit:(id:string)=>void;onDelete:(id:string)=>void}){
  const ideas=[...trip.activities].filter(item=>item.status==='suggested').sort((a,b)=>b.votes.length-a.votes.length||a.title.localeCompare(b.title));
  return <Page title="Ideas" eyebrow="Decide together" description="Suggestions stay separate from the real itinerary until the group is ready." action={canEdit?<button className="wl-primary" onClick={onAdd}><Plus size={16}/> Suggest something</button>:undefined}>
    <div className="wl-ideas-intro"><div><Heart size={22}/><span><b>Vote first. Plan second.</b><p>Active travelers can vote; editors promote the ideas that become part of the trip.</p></span></div><strong>{ideas.length} open</strong></div>
    <div className="wl-idea-grid">{ideas.map(item=><article className="wl-idea-card" key={item.id}><div className="wl-idea-head"><span className={`wl-category ${item.category}`}>{categoryIcon(item.category)}</span><StatusBadge status="suggested"/>{canEdit&&<><button onClick={()=>onEdit(item.id)} aria-label={`Edit ${item.title}`}><Settings2 size={15}/></button><button onClick={()=>onDelete(item.id)} aria-label={`Delete ${item.title}`}><Trash2 size={15}/></button></>}</div><h3>{item.title}</h3>{item.location&&<button className="wl-location" onClick={()=>openGoogleMaps(item.location)}><MapPin size={13}/>{item.location}</button>}<p>{item.note||'No extra notes yet.'}</p><div className="wl-idea-meta"><span>{dateLabel(item.date)} · {displayTime(item.time)}</span><span>{item.cost===0?'Free':money(item.cost)}</span><span>Suggested by {memberName(trip,item.createdBy)}</span></div><div className="wl-voters">{item.votes.map(id=>trip.members.find(member=>member.id===id&&member.status==='active')).filter((member):member is NonNullable<typeof member>=>Boolean(member)).map(member=><Avatar member={member} small key={member.id}/>)}<span>{item.votes.length} vote{item.votes.length===1?'':'s'}</span></div><div className="wl-idea-actions">{canVote&&<button className={item.votes.includes(currentUserId)?'voted':''} onClick={()=>onVote(item.id)}><Heart size={15}/>{item.votes.includes(currentUserId)?'Voted':'Vote'}</button>}{canEdit&&<><button onClick={()=>onPromote(item.id,'planned')}>Add to plan</button><button className="primary" onClick={()=>onPromote(item.id,'confirmed')}><Check size={15}/> Confirm</button></>}</div></article>)}{ideas.length===0&&<Empty title="No open suggestions" text="The group has made every decision for now."/>}</div>
  </Page>;
}

export function Places({trip,canEdit,onAdd,onEdit,onDelete,onPlan}:{trip:Trip;canEdit:boolean;onAdd:()=>void;onEdit:(id:string)=>void;onDelete:(id:string)=>void;onPlan:(id:string)=>void}){
  const [filter,setFilter]=useState('');
  const places=trip.places.filter(place=>`${place.name} ${place.category} ${place.neighborhood} ${place.note}`.toLowerCase().includes(filter.toLowerCase()));
  return <Page title="Saved places" eyebrow="Trip wishlist" description="Keep interesting spots here, then turn the ones you choose into itinerary plans." action={canEdit?<button className="wl-primary" onClick={onAdd}><Plus size={16}/> Save a place</button>:undefined}>
    <div className="wl-section-search"><Search size={16}/><input aria-label="Search saved places" value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Search saved places…"/></div><div className="wl-place-grid">{places.map(place=><article className="wl-place-card" key={place.id}><div className="wl-place-art"><MapPin/><span>{place.category}</span></div><div className="wl-place-body"><small>{place.neighborhood||'Saved place'}</small><h3>{place.name}</h3><p>{place.note||'No note added.'}</p><span>Saved by {memberName(trip,place.createdBy)}</span></div><div className="wl-place-actions"><button onClick={()=>openGoogleMaps(`${place.name}, ${trip.destination}`)}><Map size={15}/> Google Maps</button>{canEdit&&<button onClick={()=>onPlan(place.id)}><CalendarCheck2 size={15}/> Add to itinerary</button>}{canEdit&&<button className="icon" onClick={()=>onEdit(place.id)} aria-label={`Edit ${place.name}`}><Settings2 size={15}/></button>}{canEdit&&<button className="icon danger" onClick={()=>onDelete(place.id)} aria-label={`Remove ${place.name}`}><Trash2 size={15}/></button>}</div></article>)}{places.length===0&&<Empty title="No places match" text="Try a different search or save a new place."/>}</div>
  </Page>;
}

export function Budget({trip,currentUserId,canEdit,onAdd,onEdit,onDelete}:{trip:Trip;currentUserId:string;canEdit:boolean;onAdd:()=>void;onEdit:(id:string)=>void;onDelete:(id:string)=>void}){
  const [filter,setFilter]=useState('');
  const spent=trip.expenses.reduce((sum,item)=>sum+item.amount,0);
  const categories=['Lodging','Food','Transportation','Activities','Shopping','Other'] as const;
  const categoryTotals=categories.map(category=>({category,total:trip.expenses.filter(item=>item.category===category).reduce((sum,item)=>sum+item.amount,0)})).filter(item=>item.total>0);
  const ledger=trip.expenses.filter(item=>`${item.description} ${item.category}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const memberBalances=balances(trip);
  const settlements=calculateSettlements(trip);
  const usedPct=trip.budget>0?spent/trip.budget*100:spent>0?100:0;
  return <Page title="Budget" eyebrow="Money together" description="Track actual trip expenses separately from itinerary estimates, with cent-accurate splits and settlements." action={canEdit?<button className="wl-primary" onClick={onAdd}><Plus size={16}/> Add expense</button>:undefined}>
    <section className={`wl-budget-hero${spent>trip.budget&&trip.budget>0?' over':''}`}><div><span>Total trip budget</span><strong>{money(trip.budget)}</strong><p>{money(spent)} spent · <BudgetSummary budget={trip.budget} spent={spent}/></p><div role="progressbar" aria-label="Budget used" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,Math.round(usedPct))}><i style={{width:`${Math.min(100,usedPct)}%`}}/></div></div><div className="wl-budget-ring" style={{'--budget-used':`${Math.min(100,usedPct)}%`} as CSSProperties}><span><b>{Math.round(usedPct)}%</b><small>used</small></span></div></section>
    <p className="wl-budget-note">Itinerary costs are planning estimates only. The budget totals below use actual expenses, so the same cost is never counted twice.</p>
    <div className="wl-budget-grid"><section className="wl-panel"><PanelHead eyebrow="Ledger" title="Expenses"/><div className="wl-section-search compact"><Search size={15}/><input aria-label="Search expenses" value={filter} onChange={event=>setFilter(event.target.value)} placeholder="Search expenses…"/></div><div className="wl-expense-list">{ledger.map(expense=><div className="wl-expense-row" key={expense.id}><span className="wl-expense-icon"><Receipt size={16}/></span><div><b>{expense.description}</b><small>{expense.category} · Paid by {memberName(trip,expense.paidBy)} · {splitLabel(expense,trip)}</small></div><strong>{money(expense.amount)}</strong>{canEdit&&<button onClick={()=>onEdit(expense.id)} aria-label={`Edit ${expense.description}`}><Settings2 size={14}/></button>}{canEdit&&<button onClick={()=>onDelete(expense.id)} aria-label={`Delete ${expense.description}`}><Trash2 size={14}/></button>}</div>)}{ledger.length===0&&<Empty title="No expenses match" text="Try a different search or add the first real trip expense."/>}</div></section><aside className="wl-budget-side"><section className="wl-panel"><PanelHead eyebrow="Breakdown" title="By category"/><div className="wl-category-breakdown">{categoryTotals.map(item=><div key={item.category}><span><b>{item.category}</b><strong>{money(item.total)}</strong></span><div><i style={{width:`${item.total/Math.max(spent,1)*100}%`}}/></div></div>)}{categoryTotals.length===0&&<p className="wl-panel-note">No actual expenses yet.</p>}</div></section><section className="wl-panel"><PanelHead eyebrow="Group balances" title="Who owes whom"/><div className="wl-balance-list">{memberBalances.map(({member,paid,share,balance})=><div key={member.id}><Avatar member={member} small/><span><b>{member.name}{member.id===currentUserId?' (you)':''}</b><small>Paid {money(paid)} · Share {money(share)}</small></span><strong className={balance>=0?'positive':'negative'}>{balance>=0?'+':''}{money(balance)}</strong></div>)}</div><div className="wl-settlements">{settlements.length>0?settlements.map((item,index)=><p key={`${item.from}-${item.to}-${index}`}><b>{memberName(trip,item.from)}</b> owes <b>{memberName(trip,item.to)}</b> {money(item.amount)}</p>):<p>Everyone is settled up.</p>}</div></section></aside></div>
  </Page>;
}

export function Packing({trip,currentUserId,canEdit,onAdd,onToggle,onDelete}:{trip:Trip;currentUserId:string;canEdit:boolean;onAdd:()=>void;onToggle:(id:string)=>void;onDelete:(id:string)=>void}){
  const shared=trip.packing.filter(item=>item.scope==='shared');
  const personal=trip.packing.filter(item=>item.scope==='personal'&&item.assignedTo===currentUserId);
  const ready=trip.packing.filter(item=>item.done).length;
  return <Page title="Packing" eyebrow="Get ready" description="Keep personal items personal and make shared responsibility obvious." action={canEdit?<button className="wl-primary" onClick={onAdd}><Plus size={16}/> Add item</button>:undefined}>
    <div className="wl-packing-progress"><span><Luggage size={20}/><div><b>{ready} of {trip.packing.length} ready</b><small>{ready===trip.packing.length&&trip.packing.length>0?'Everything on the list is ready.':'A few things left before departure.'}</small></div></span><strong>{Math.round(ready/Math.max(trip.packing.length,1)*100)}%</strong></div><div className="wl-packing-grid"><PackingGroup title="Shared trip items" subtitle="One person owns each item so the group doesn’t duplicate it." items={shared} trip={trip} canEdit={canEdit} onToggle={onToggle} onDelete={onDelete}/><PackingGroup title="My items" subtitle="Only personal items assigned to you." items={personal} trip={trip} canEdit={canEdit} onToggle={onToggle} onDelete={onDelete}/></div>
  </Page>;
}

function PackingGroup({title,subtitle,items,trip,canEdit,onToggle,onDelete}:{title:string;subtitle:string;items:PackingItem[];trip:Trip;canEdit:boolean;onToggle:(id:string)=>void;onDelete:(id:string)=>void}){
  return <section className="wl-panel"><PanelHead eyebrow="Checklist" title={title}/><p className="wl-panel-copy">{subtitle}</p><div className="wl-packing-list">{items.map(item=><div key={item.id} className={item.done?'done':''}><button className="wl-check" onClick={()=>onToggle(item.id)} disabled={!canEdit} aria-label={`${item.done?'Mark not packed':'Mark packed'}: ${item.label}`}>{item.done?<Check size={14}/>:null}</button><span><b>{item.label}</b><small>{item.scope==='shared'?`${memberName(trip,item.assignedTo)} is bringing this`:'Personal item'}</small></span>{canEdit&&<button className="wl-row-delete" onClick={()=>onDelete(item.id)} aria-label={`Delete ${item.label}`}><Trash2 size={14}/></button>}</div>)}{items.length===0&&<Empty title="Nothing here yet" text="Add an item when something comes to mind."/>}</div></section>;
}

export function NotesAndBookings({trip,canEdit,onAddNote,onEditNote,onDeleteNote,onAddReservation,onEditReservation,onDeleteReservation}:{trip:Trip;canEdit:boolean;onAddNote:()=>void;onEditNote:(id:string)=>void;onDeleteNote:(id:string)=>void;onAddReservation:()=>void;onEditReservation:(id:string)=>void;onDeleteReservation:(id:string)=>void}){
  const reservations=[...trip.reservations].sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  return <Page title="Notes & bookings" eyebrow="Trip details" description="Keep practical information available to the people on the trip without crowding the itinerary."><div className="wl-notes-grid"><section><div className="wl-subhead"><div><span>Shared knowledge</span><h2>Trip notes</h2></div>{canEdit&&<button onClick={onAddNote}><Plus size={15}/> Add note</button>}</div><div className="wl-note-grid">{trip.notes.map(note=><article key={note.id}><div><FileText size={18}/><small>Updated {relativeDate(note.updatedAt)}</small></div><h3>{note.title}</h3><p>{note.body}</p><footer><span>By {memberName(trip,note.createdBy)}</span>{canEdit&&<><button onClick={()=>onEditNote(note.id)}>Edit</button><button onClick={()=>onDeleteNote(note.id)}>Delete</button></>}</footer></article>)}{trip.notes.length===0&&<Empty title="No trip notes yet" text="Add practical context that does not belong on a specific activity."/>}</div></section><section><div className="wl-subhead"><div><span>Private trip details</span><h2>Reservations</h2></div>{canEdit&&<button onClick={onAddReservation}><Plus size={15}/> Add booking</button>}</div><p className="wl-booking-privacy">Confirmation/reference values stay inside this browser-local workspace and are never included in Share summary.</p><div className="wl-booking-list">{reservations.map(item=><article key={item.id}><span className="wl-booking-icon">{reservationIcon(item.type)}</span><div><small>{item.type} · {dateLabel(item.date)} · {displayTime(item.time)}</small><h3>{item.title}</h3>{item.location&&<button onClick={()=>openGoogleMaps(item.location)}><MapPin size={13}/>{item.location}</button>}{item.confirmation&&<p><b>Confirmation:</b> {item.confirmation}</p>}{item.note&&<p>{item.note}</p>}</div><div>{canEdit&&<button onClick={()=>onEditReservation(item.id)} aria-label={`Edit ${item.title}`}><Settings2 size={15}/></button>}{canEdit&&<button onClick={()=>onDeleteReservation(item.id)} aria-label={`Delete ${item.title}`}><Trash2 size={15}/></button>}</div></article>)}{reservations.length===0&&<Empty title="No bookings yet" text="Add flights, lodging, events, or other reservations when they are confirmed."/>}</div></section></div></Page>;
}

export function Travelers({trip,currentUserId,isOwner,onInvite,onRole,onRemove}:{trip:Trip;currentUserId:string;isOwner:boolean;onInvite:()=>void;onRole:(id:string,role:MemberRole)=>void;onRemove:(id:string)=>void}){
  const visible=trip.members.filter(member=>member.status!=='removed');
  const activeCount=visible.filter(member=>member.status==='active').length;
  const pendingCount=visible.filter(member=>member.status==='pending').length;
  return <Page title="Travelers" eyebrow="Plan together" description="Model who is coming and what each person may change. Cloud invitation delivery is not enabled yet." action={isOwner?<button className="wl-primary" onClick={onInvite}><UserPlus size={16}/> Add pending invite</button>:undefined}>
    <div className="wl-collab-boundary" role="note"><ShieldCheck size={20}/><div><b>Local collaboration demo</b><p>Roles, votes, invitations, and shared workflows are fully modeled in this browser. They do not synchronize to other devices until Firestore is connected.</p></div></div>
    <div className="wl-role-guide"><div><ShieldCheck size={22}/><span><b>Owner</b><p>Trip settings, member roles, archive/delete, and all editing.</p></span></div><div><Settings2 size={22}/><span><b>Editor</b><p>Itinerary, ideas, places, expenses, packing, notes, and bookings.</p></span></div><div><BookOpen size={22}/><span><b>Viewer</b><p>Read-only planning access; active viewers can still vote on ideas.</p></span></div></div>
    <section className="wl-panel"><PanelHead eyebrow="Trip members" title={`${activeCount} active · ${pendingCount} pending`}/><div className="wl-traveler-list">{visible.map(member=><div key={member.id} className={member.status==='pending'?'pending':''}><Avatar member={member}/><span><b>{member.name}{member.id===currentUserId?' (you)':''}</b><small>{member.email||'No email'} · {member.status==='pending'?'Pending locally — no invitation email has been sent':'Active traveler'}</small></span>{isOwner&&member.id!==currentUserId&&member.status==='active'?<select aria-label={`Role for ${member.name}`} value={member.role} onChange={event=>onRole(member.id,event.target.value as MemberRole)}><option value="editor">Editor</option><option value="viewer">Viewer</option></select>:<strong>{member.role}</strong>}{isOwner&&member.id!==currentUserId&&<button onClick={()=>onRemove(member.id)} aria-label={`Remove ${member.name}`}><Trash2 size={15}/></button>}</div>)}</div></section>
  </Page>;
}

export function ActivityLog({trip}:{trip:Trip}){
  return <Page title="Activity" eyebrow="What changed" description="A lightweight local history makes a busy trip easier to follow and preserves authorship even after a traveler leaves."><section className="wl-panel"><div className="wl-history">{trip.history.map(event=>{const member=trip.members.find(item=>item.id===event.memberId)??{id:'unknown',name:'Former traveler',email:'',initials:'?',role:'viewer' as const,status:'removed' as const};return <div key={event.id}><Avatar member={member} small/><span><p><b>{memberName(trip,event.memberId)}</b> {event.text}</p><small>{relativeDate(event.createdAt)}</small></span></div>})}{trip.history.length===0&&<Empty title="No changes recorded yet" text="Meaningful edits will appear here."/>}</div></section></Page>;
}
